### ISSUE TITLE
Keyboard Colors Match Theme

### ISSUE THREAD

**Issue by hchampury1** [Simon-Blamo/accessible-hangman#13]
Keyboard colors that need to change to match certainThemes:
- Black & White is good as is
- Blue-Yellow
  - Blue highlight when hover over letter - make Green?
- Red Green Theme needs to change
  - Correct letter - Blue ?
  - Incorrect letter - Yellow ?
  - Blue highlight when hover over letter - make darker blue?
- Monochromatic is good as is
- Dark Mode is good as is

**Comment by Simon-Blamo** [comment]
My current implementation also increases the width of the button, when it is used as guess. Will look into this more later on.

**Comment by Simon-Blamo** [comment]
Fixed color issue. However, was unable to find how to implement hover colors. Would be big if someone could figure it out. Unassigning.

**Comment by hchampury1** [comment]
Adjusted colors a bit to match color blindess colors a bit better & a bit more easy on the eye

**Comment by hchampury1** [comment]
Fixed the hovering colors on branch: Milestone2-HC
