### ISSUE TITLE
Turn OFF Voice Command

### ISSUE THREAD

**Issue by hchampury1** [Simon-Blamo/accessible-hangman#21]
- Application breaks if you turn off while game speaks

**Comment by hchampury1** [comment]
sometimes application is still running even after closing
- happens when you close while the game speaks

**Comment by hchampury1** [comment]
program continues running when you close program while the narrator speaks

**Comment by Simon-Blamo** [comment]
fixed ig

**Comment by hchampury1** [comment]
still breaks after testing but not a big deal if it can't be fixed

**Comment by hchampury1** [comment]
fixed issue
