### ISSUE TITLE
Number of chances not updating (audio)

### ISSUE THREAD

**Issue by hchampury1** [Simon-Blamo/accessible-hangman#38]
when you guess incorrectly - changes to from 11 to 10
next incorrect guess - stays as 10

**Comment by hchampury1** [comment]
added number of chances label so user can see how many guesses they have left

**Comment by Burkel4** [comment]
test: play first game start new game midway & test num of chances

**Comment by Simon-Blamo** [comment]
?? why do i gotta test this?

**Comment by Simon-Blamo** [comment]
modified some code, worked when I tested.
