### ISSUE TITLE
Dark mode theme

### ISSUE THREAD

**Issue by hchampury1** [Simon-Blamo/accessible-hangman#9]
-background color & button colors not showing
-turnings theme menu & font menu white
-can't read text

**Comment by hchampury1** [comment]
![darkmode](https://github.com/user-attachments/assets/7d44517a-767a-4b71-81ae-d812d09adc1d)

**Comment by Simon-Blamo** [comment]
Fixed problems listed in issue.

The hangman image is still hard to see. We could discuss what to do further from here later.

![Screenshot 2024-11-08 173537](https://github.com/user-attachments/assets/b05eb616-112a-4ef7-af4f-9c97e959ce04)

**Comment by hchampury1** [comment]
will fix this in other issue with hangman colors
